swiqlisp-install now performs an actual installation, i.e., executbale files are copied to /usr/{s}bin, swiqlisp.rc it copied to /etc/ and all other files are copied to SYSUSR_HOME.  swiqlisp-uninstall adapted to remove them.

diff --git a/swiqlisp b/swiqlisp
--- a/swiqlisp
+++ b/swiqlisp
@@ -26,27 +26,53 @@
 #  Use the script swiqlisp-install to install Quicklisp site-wide in the first
 #  instance.
 
-#-----------------------------------------------------------------------------
-# Initialise variables and perform sanity checks
-
 #set -e                         # grep returns exit code 1 if no matches are found
-source swiqlisp.rc
-source swiqlisp-utils
 
-TMP_DIR=$SYSUSR_HOME/tmp
-LOG_DIR=$TMP_DIR/log
-ACTION=$1; OBJECT=$2
-usage="Usage: sudo ./swiqlisp <action> [<object>]"
+#-----------------------------------------------------------------------------
+# utility function
+ensure_no_trailing_slash () {
+    if test ${1: -1} = /; then echo -n ${1:0: -1}
+    else echo -n $1
+    fi ; }
 
+#-----------------------------------------------------------------------------
+# source /etc/swiqlisp.rc & $SYSUSR_HOME/swiqlisp-utils
+
+if test -r /etc/swiqlisp.rc; then
+    source /etc/swiqlisp.rc
+else
+    echo "Error: /etc/swiqlisp.rc not found.  Aborting."
+    exit 1
+fi
+
+# remove trailing slash in SYSUSR_HOME (if any)
+SYSUSR_HOME=$(ensure_no_trailing_slash $SYSUSR_HOME)
+
+if test -r $SYSUSR_HOME/swiqlisp-utils; then
+    source $SYSUSR_HOME/swiqlisp-utils
+else
+    echo "Error: $SYSUSR_HOME/swiqlisp-utils not found.  Aborting."
+    exit 1
+fi
+
+# debugging
+if test $DEBUG = on; then
+    echo "debug: SYSUSR=$SYSUSR"
+    echo "debug: SYSUSR_HOME=$SYSUSR_HOME";
+fi;
+
+#-----------------------------------------------------------------------------
+# variables, sanity checks on command line args, lisp check/setup
+
+TMP_DIR=$SYSUSR_HOME/tmp; LOG_DIR=$TMP_DIR/log; ACTION=$1; OBJECT=$2
+
+usage="Usage: [sudo] swiqlisp <query-or-action> [<object>]"
 check_help "$usage"
-
 if test \( "${ACTION:0:7}" = "install" -o "${ACTION:0:6}" = "remove" \) -a \
         -z "$OBJECT"; then
     echo "$usage"; exit 0
 fi
 
-check_root_privileges # FIXME - unprivileged users should be able to do some things
-check_sysusr_home
 check_lisp_and_setup_accordingly
 
 #-----------------------------------------------------------------------------
@@ -138,6 +164,7 @@ removed_systems_report () {
     eval "$LISP_COMMAND" ; }
 
 install () {
+    check_root_privileges
     EVAL="'(install-$1 \"$OBJECT\" $2)'"
     ERRLOG="$LOG_DIR/install-${1}_${OBJECT}_error.log"
     COMMANDS="$eval $EVAL $quit 2>$ERRLOG"
@@ -153,6 +180,7 @@ install () {
     additional_systems_report ; }
 
 uninstall () {
+    check_root_privileges
     EVAL="'(uninstall-$1 \"$OBJECT\")'"
     ERRLOG="$LOG_DIR/uninstall-${1}_${OBJECT}_error.log"
     COMMANDS="$eval $EVAL $quit 2>$ERRLOG"
@@ -168,6 +196,7 @@ uninstall () {
     removed_systems_report ; }
 
 self_update () {
+    check_root_privileges
     EVAL="'(self-update)'"
     ERRLOG="$LOG_DIR/self-update_error.log"
     COMMANDS="$eval $EVAL $quit 2>$ERRLOG"
@@ -180,6 +209,7 @@ self_update () {
     fi ; }
 
 update_systems () {
+    check_root_privileges
     EVAL="'(update-systems)'"
     ERRLOG="$LOG_DIR/update-systems_error.log"
     COMMANDS="$eval $EVAL $quit 2>$ERRLOG"
diff --git a/swiqlisp-install b/swiqlisp-install
--- a/swiqlisp-install
+++ b/swiqlisp-install
@@ -26,15 +26,35 @@
 #  a day-to-day basis.
 
 #-----------------------------------------------------------------------------
-# Initialise variables and perform sanity checks
+# utility function
+ensure_no_trailing_slash () {
+    if test ${1: -1} = /; then echo -n ${1:0: -1}
+    else echo -n $1
+    fi ; }
+
+#-----------------------------------------------------------------------------
+# source ./swiqlisp.rc, ./swiqlisp-utils & perform sanity checks
 
 source swiqlisp.rc
 source swiqlisp-utils
 check_help "Usage: sudo ./swiqlisp-install"
 check_root_privileges
-check_sysusr_home
 check_lisp_and_setup_accordingly
 
+# remove trailing slash in SYSUSR_HOME (if any)
+SYSUSR_HOME=$(ensure_no_trailing_slash $SYSUSR_HOME)
+
+# check that SYSUSR_HOME parent directory exists
+if test ! -d $(dirname $SYSUSR_HOME); then
+    echo "Error: $(dirname $SYSUSR_HOME) not found."
+    exit 1
+fi
+
+# debugging
+if test $DEBUG = on; then
+    echo "debug: SYSUSR=$SYSUSR"
+    echo "debug: SYSUSR_HOME=$SYSUSR_HOME";
+fi;
 
 #-----------------------------------------------------------------------------
 # Create and populate SYSUSR_HOME
@@ -94,19 +114,28 @@ touch $SYSUSR_HOME/tmp/installed-systems.current \
       $SYSUSR_HOME/tmp/installed-systems.added \
       $SYSUSR_HOME/tmp/installed-systems.removed \
       $SYSUSR_HOME/tmp/installed-systems.old
-      $SYSUSR_HOME/tmp/installed-systems.added \
-      $SYSUSR_HOME/tmp/installed-systems.removed \
-      $SYSUSR_HOME/tmp/installed-systems.old
 
 # setup installed-systems dir
 mkdir -p $SYSUSR_HOME/installed-systems
 
-# install swiqlisp.lisp and swiqlisp-slime-helper.el
-cp -f swiqlisp.lisp swiqlisp-slime-helper.el $SYSUSR_HOME
+# copy files
+cp -f \
+    swiqlisp-sbcl \
+    swiqlisp-slime-helper.el \
+    swiqlisp-utils \
+    swiqlisp.lisp \
+    $SYSUSR_HOME
 
-# quicklisp/ and .cache/ are already owned by SYSUSR
-# so there's no harm in this blanket chown
+# no harm in this blanket chown
 chown -R $SYSUSR:nogroup $SYSUSR_HOME
+
+#-----------------------------------------------------------------------------
+# /etc, /usr/bin & /usr/sbin
+
+cp -f swiqlisp.rc     /etc
+cp -f swiqlisp        /usr/bin
+cp -f swiqlisp-stanza /usr/sbin
+chmod a+x swiqlisp swiqlisp-stanza
 
 #-----------------------------------------------------------------------------
 # Install Quicklisp
@@ -139,7 +168,7 @@ fi
 
 #-----------------------------------------------------------------------------
 # add/remove the swiQlisp stanza
-source swiqlisp-stanza
+swiqlisp-stanza
 
 #-----------------------------------------------------------------------------
 echo "swiQlisp successfully installed."
diff --git a/swiqlisp-stanza b/swiqlisp-stanza
--- a/swiqlisp-stanza
+++ b/swiqlisp-stanza
@@ -33,13 +33,44 @@
 #
 
 #-----------------------------------------------------------------------------
-source swiqlisp.rc
-source swiqlisp-utils
+# utility function
+ensure_no_trailing_slash () {
+    if test ${1: -1} = /; then echo -n ${1:0: -1}
+    else echo -n $1
+    fi ; }
+
+#-----------------------------------------------------------------------------
+# source /etc/swiqlisp.rc & $SYSUSR_HOME/swiqlisp-utils
+
+if test -r /etc/swiqlisp.rc; then
+    source /etc/swiqlisp.rc
+else
+    echo "Error: /etc/swiqlisp.rc not found.  Aborting."
+    exit 1
+fi
+
+# remove trailing slash in SYSUSR_HOME (if any)
+SYSUSR_HOME=$(ensure_no_trailing_slash $SYSUSR_HOME)
+
+if test -r $SYSUSR_HOME/swiqlisp-utils; then
+    source $SYSUSR_HOME/swiqlisp-utils
+else
+    echo "Error: $SYSUSR_HOME/swiqlisp-utils not found.  Aborting."
+    exit 1
+fi
+
+# debugging
+if test $DEBUG = on; then
+    echo "debug: SYSUSR=$SYSUSR"
+    echo "debug: SYSUSR_HOME=$SYSUSR_HOME";
+fi;
+
+#-----------------------------------------------------------------------------
+# sanity checks on command line args, lisp check/setup
+
 check_help "Usage: sudo ./swiqlisp-stanza"
 check_root_privileges
-check_sysusr_home
 check_lisp_and_setup_accordingly # needed for value of SYSINIT_FILE
-
 
 #-----------------------------------------------------------------------------
 # write/remove init file stanza
