Unprivileged system user reintroduced.  Use of local tmp/ directory for installed-systems.* files and error logs.  The word 'project' has been dropped in favour of 'release' (which is what Quicklisp uses).  All commands now implemented.

diff --git a/swiqlisp b/swiqlisp
--- a/swiqlisp
+++ b/swiqlisp
@@ -27,87 +27,113 @@
 #  instance.
 
 #-----------------------------------------------------------------------------
+# Initialise variables and perform sanity checks
+
 #set -e                         # grep returns exit code 1 if no matches are found
 source swiqlisp.rc
 source swiqlisp-utils
 
 ACTION=$1; OBJECT=$2
 usage="Usage: sudo ./swiqlisp <action> [<object>]"
-help_requested "$usage"
+
+check_help "$usage"
+
 if test \( "${ACTION:0:7}" = "install" -o "${ACTION:0:6}" = "remove" \) -a \
         -z "$OBJECT"; then
     echo "$usage"; exit 0
 fi
 
-check_root # FIXME - unprivileged users should be able to do some things
-swiqlisp_paths
-lisp_setup
-LISP_COMMAND='$SU -c "$INVOC $load $SWIQLISP_DIR/setup $load swiqlisp.lisp $COMMANDS"'
+check_root_privileges # FIXME - unprivileged users should be able to do some things
+check_sysusr_home
+check_lisp_and_setup_accordingly
 
 #-----------------------------------------------------------------------------
 # shell functions
+
+TMP_DIR=$SYSUSR_HOME/tmp/
+
 rotate_installed_systems_files () {
-    echo -n "" > $SWIQLISP_DIR/installed-systems.added
-    echo -n "" > $SWIQLISP_DIR/installed-systems.removed
-    mv -f $SWIQLISP_DIR/installed-systems.current \
-        $SWIQLISP_DIR/installed-systems.old
-    # FIXME - how to handle multiple dists?
-    cat $SWIQLISP_DIR/dists/quicklisp/installed/systems/*.txt | sort \
-        > $SWIQLISP_DIR/installed-systems.current
-    # systems that have just been added
-    grep -v -f $SWIQLISP_DIR/installed-systems.old \
-        $SWIQLISP_DIR/installed-systems.current \
-        > $SWIQLISP_DIR/installed-systems.added
-    # systems that have just been removed
-    grep -v -f $SWIQLISP_DIR/installed-systems.current \
-        $SWIQLISP_DIR/installed-systems.old \
-        > $SWIQLISP_DIR/installed-systems.removed; }
+    # truncate the two 'difference' files
+    echo -n "" > $TMP_DIR/installed-systems.added
+    echo -n "" > $TMP_DIR/installed-systems.removed
+    # 'current' is now 'old'
+    mv -f $TMP_DIR/installed-systems.current \
+        $TMP_DIR/installed-systems.old
+    chown $SYSUSR:nogroup $TMP_DIR/installed-systems.old
+    # update 'current' (FIXME - how to handle multiple dists?)
+    cat $SYSUSR_HOME/quicklisp/dists/quicklisp/installed/systems/*.txt 2>/dev/null \
+	| sort > $TMP_DIR/installed-systems.current # [1]
+    chown $SYSUSR:nogroup $TMP_DIR/installed-systems.current
+    # establish which systems have just been added
+    grep -v -f $TMP_DIR/installed-systems.old \
+        $TMP_DIR/installed-systems.current \
+        > $TMP_DIR/installed-systems.added
+    # establish which systems have just been removed
+    grep -v -f $TMP_DIR/installed-systems.current \
+        $TMP_DIR/installed-systems.old \
+        > $TMP_DIR/installed-systems.removed; }
 
 write_links_to_additional_system_files () {
-    for system in $(cat $SWIQLISP_DIR/installed-systems.added); do
-        ln -s  ../$system $SWIQLISP_DIR/installed-systems/
+    for system in $(cat $TMP_DIR/installed-systems.added); do
+        ln -s  ../quicklisp/$system $SYSUSR_HOME/installed-systems/
     done; }
 
 remove_links_to_removed_system_files () {
-    for system in $(cat $SWIQLISP_DIR/installed-systems.removed); do
-        echo remove me - $system
+    for system in $(cat $TMP_DIR/installed-systems.removed); do
+	rm $SYSUSR_HOME/installed-systems/$(basename $system)
     done; }
 
 refresh_system_links () {
-    # for debugging purposes only
-    rm -f $SWIQLISP_DIR/installed-systems/*.asd
-    for system in $(cat $SWIQLISP_DIR/installed-systems.current); do
-        ln -s  ../$system $SWIQLISP_DIR/installed-systems/
+    rm -f $SYSUSR_HOME/installed-systems/*.asd
+    for system in $(cat $TMP_DIR/installed-systems.current); do
+        ln -s  ../quicklisp/$system $SYSUSR_HOME/installed-systems/
     done; }
 
+
 #-----------------------------------------------------------------------------
-# lisp functions
+# lisp command & functions which use it
+
+LISP_COMMAND='$SU -c \
+"$INVOC $load $SYSUSR_HOME/quicklisp/setup $load swiqlisp.lisp $COMMANDS" \
+$SYSUSR'
 
 list () {
     EVAL1="'(list-installed-$1)'"
     EVAL2="'(list-available-$1)'"
     COMMANDS="$eval $EVAL1 $eval $EVAL2 $quit"
-    if test $DEBUG = on; then eval echo $LISP_COMMAND | tr -s \ ; fi
-    eval $LISP_COMMAND; }
+    [ $DEBUG = on ] && eval echo "debug: $LISP_COMMAND"
+    eval "$LISP_COMMAND" ; } # $LISP_COMMAND must be quoted here
+
+list_release_systems () {
+    EVAL="'(list-release-systems \"$OBJECT\")'"
+    COMMANDS="$eval $EVAL $quit"
+    [ $DEBUG = on ] && eval echo "debug: $LISP_COMMAND"
+    eval "$LISP_COMMAND" ; } # $LISP_COMMAND must be quoted here
 
 system_apropos () {
     EVAL="'(swiqlisp-apropos \"$OBJECT\")'"
     COMMANDS="$eval $EVAL $quit"
-    if test $DEBUG = on; then eval echo $LISP_COMMAND | tr -s \ ; fi
-    eval $LISP_COMMAND; }
+    [ $DEBUG = on ] && eval echo "debug: $LISP_COMMAND"
+    eval "$LISP_COMMAND" ; }
 
 additional_systems_report () {
     EVAL="'(additional-systems-report)'"
     COMMANDS="$eval $EVAL $quit"
-    if test $DEBUG = on; then eval echo $LISP_COMMAND | tr -s \ ; fi
-    eval $LISP_COMMAND; }
+    [ $DEBUG = on ] && eval echo "debug: $LISP_COMMAND"
+    eval "$LISP_COMMAND"; }
+
+removed_systems_report () {
+    EVAL="'(removed-systems-report)'"
+    COMMANDS="$eval $EVAL $quit"
+    [ $DEBUG = on ] && eval echo "debug: $LISP_COMMAND"
+    eval "$LISP_COMMAND" ; }
 
 install () {
     EVAL="'(install-$1 \"$OBJECT\" $2)'"
     ERRLOG="/tmp/install-${1}_${OBJECT}_error.log"
     COMMANDS="$eval $EVAL $quit 2>$ERRLOG"
-    if test $DEBUG = on; then eval echo $LISP_COMMAND | tr -s \ ; fi
-    eval $LISP_COMMAND
+    [ $DEBUG = on ] && eval echo "debug: $LISP_COMMAND"
+    eval "$LISP_COMMAND"
     if [ -s $ERRLOG ]; then
         echo -e "\n\nLisp output on stderr. See $ERRLOG for more information.\n"
     else # success, so
@@ -115,21 +141,60 @@ install () {
     fi
     rotate_installed_systems_files
     write_links_to_additional_system_files
-    additional_systems_report ;}
+    additional_systems_report ; }
+
+uninstall () {
+    EVAL="'(uninstall-$1 \"$OBJECT\")'"
+    ERRLOG="/tmp/uninstall-${1}_${OBJECT}_error.log"
+    COMMANDS="$eval $EVAL $quit 2>$ERRLOG"
+    [ $DEBUG = on ] && eval echo "debug: $LISP_COMMAND"
+    eval "$LISP_COMMAND"
+    if [ -s $ERRLOG ]; then
+        echo -e "\n\nLisp output on stderr. See $ERRLOG for more information.\n"
+    else # success, so
+        rm $ERRLOG # because it's empty
+    fi
+    rotate_installed_systems_files
+    remove_links_to_removed_system_files
+    removed_systems_report ; }
+
+self_update () {
+    EVAL="'(self-update)'"
+    ERRLOG="/tmp/self-update_error.log"
+    COMMANDS="$eval $EVAL $quit 2>$ERRLOG"
+    [ $DEBUG = on ] && eval echo "debug: $LISP_COMMAND"
+    eval "$LISP_COMMAND"
+    if [ -s $ERRLOG ]; then
+        echo -e "\n\nLisp output on stderr. See $ERRLOG for more information.\n"
+    else # success, so
+        rm $ERRLOG # because it's empty
+    fi ; }
 
 #-----------------------------------------------------------------------------
 # top level
 
 case $ACTION in
-                   projects) list projects;;
-                    systems) list systems;;
-            project-systems) list project_systems;; # unimplemented
-           #install-project) install project;;
-     install|install-system) install system;;
-        install-and-compile) install system t;;
-         #uninstall-project) uninstall project;;    # unimplemented
- uninstall|uninstall-system) uninstall system;;     # unimplemented
-             system-apropos) system_apropos;;
-           refresh-syslinks) refresh_system_links;;
-                          *) echo "Unknown action.  Aborting." && exit 1;;
+    #          command line  shell function       $1        $2
+    #          ------------  --------------    	  --        --
+    # queries
+                   releases) list              	  releases     ;;
+                    systems) list              	  systems      ;;
+            release-systems) list_release_systems              ;; # $OBJECT req'd
+             system-apropos) system_apropos    	               ;; # $OBJECT req'd
+    # actions
+     install|install-system) install           	  system       ;; # $OBJECT req'd
+         install-no-compile) install           	  system    t  ;; # $OBJECT req'd [2]
+ uninstall|uninstall-system) uninstall         	  system       ;; # $OBJECT req'd
+                self-update) self_update       	               ;;
+    # maintenance
+       refresh-system-links) refresh_system_links              ;;
+
+                          *) echo "Unknown action.  Aborting." && exit 1 ;;
 esac
+
+# [1] When the last system has been uninstalled, there are no .txt files
+#     remaining, so we must redirect stderr to /dev/null in order to muffle the
+#     cat.
+#
+# [2] Some systems require compilation for their dependencies to be handled
+#     correctly
diff --git a/swiqlisp-uninstall b/swiqlisp-uninstall
--- a/swiqlisp-uninstall
+++ b/swiqlisp-uninstall
@@ -26,24 +26,32 @@
 #-----------------------------------------------------------------------------
 source swiqlisp.rc
 source swiqlisp-utils
-help_requested "Usage: sudo ./swiqlisp-uninstall"
-check_root
-swiqlisp_paths
+check_help "Usage: ./swiqlisp-uninstall"
+check_root_privileges
+check_sysusr_home
 
 
 #-----------------------------------------------------------------------------
+
+if test -z "$(id -u $SYSUSR 2>/dev/null)"; then
+    # no SYSUSR
+    echo "SYSUSR ($SYSUSR) does not exist.
+
+If you are certain that swiQlisp is installed, the most likely explanation is
+that the value of SYSUSR has changed.  Please check ./swiqlisp.rc."
+    exit 1;
+fi
+
 ask "Uninstall site-wide Quicklisp?  Confirm"
 
 if test "$ans" = "y" -o "$ans" = "Y"; then
-    if test -d $SWIQLISP_DIR; then
-	rm -r $SWIQLISP_DIR
-	sleep 1
-	echo -e "Site-wide Quicklisp uninstalled."
-	source swiqlisp-stanza
-    else
-	echo -e "Directory $SWIQLISP_DIR not found.
-
-If you're certain swiQlisp is installed, the most likely explanation is that the
-value of SWIQLISP_DIR has been altered (in swiqlisp.rc)."
-    fi
+    # uninstall by removing the system user and its home directory
+    userdel --remove $SYSUSR
+    sleep 1
+    echo "Sytem user '$SYSUSR' with home directory '$SYSUSR_HOME' removed."
+    echo "swiQlisp successfully uninstalled."
+    # run swiqlisp-stanza
+    source swiqlisp-stanza
+else
+    echo "Uninstallation operation aborted."
 fi
